language: python
cache: pip

matrix:
  include:
    - env: TOXENV="flake8,isort,docs"
      python: '3.6'

install:
  - pip install --upgrade pip wheel tox
  - pip install coveralls

script:
  - tox

after_success: coveralls
